version: '3'
services:
  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      LANG: ja_JP.utf8
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: