version: '3.1'
services:
  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      LANG: ja_JP.utf8
    volumes:
      - database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    secrets:
      - db_password

volumes:
  database:

secrets:
    db_password:
      external: true
