version: '3'
services:
  db:
    image: mariadb:10.5
    restart: always
    ports: 
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: rootroot
      MARIADB_DATABASE: cmsboot
      MARIADB_USER: cmsuser
      MARIADB_PASSWORD: cmspassword
    volumes:
      - cmsboot-mariadb-data:/var/lib/mysql

volumes:
  cmsboot-mariadb-data: